@base_url = http://localhost:9000/api/v1

### Health
GET {{base_url}}/health

### Meta
GET {{base_url}}/meta

### Calendar
GET {{base_url}}/calendar?year=1940&month=10

### SEO topic pages (home / is the SPA on the frontend)

### Year / fangjia / jieqi
GET http://localhost:9000/y/2026
GET http://localhost:9000/fangjia/2026
GET http://localhost:9000/jieqi/2026
GET http://localhost:9000/jieqi/2026/lichun
GET http://localhost:9000/sitemap.xml
